ALTER TABLE connections_puzzles ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE wordle_puzzles ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE native_puzzles ADD COLUMN IF NOT EXISTS title VARCHAR(255);
